name: CI-CD-NestJS

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Node setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests (no falla si no hay tests)
      - name: Run tests
        run: npm run test --if-present -- --passWithNoTests

      # Login to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}        # Debe estar en min√∫sculas
          password: ${{ secrets.REGISTRY_TOKEN }}

      # Build image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.REGISTRY_USER }}/nestjs-greeting:latest .

      # Push image
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ secrets.REGISTRY_USER }}/nestjs-greeting:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Logging into GHCR..."
            echo "${{ secrets.REGISTRY_TOKEN }}" | sudo docker login ghcr.io -u ${{ secrets.REGISTRY_USER }} --password-stdin

            echo "Pulling new image..."
            sudo docker pull ghcr.io/${{ secrets.REGISTRY_USER }}/nestjs-greeting:latest

            echo "Stopping old container..."
            sudo docker stop nestjs-greeting || true
            sudo docker rm nestjs-greeting || true

            echo "Starting new container..."
            sudo docker run -d \
              --name nestjs-greeting \
              -p 8080:8080 \
              --restart=always \
              ghcr.io/${{ secrets.REGISTRY_USER }}/nestjs-greeting:latest

            echo "Deployment done!"
